name: peminjaman_kelas_gku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  booking_calendar: ^1.1.10
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
